### ISSUE TITLE
[BUG] Online demo seems to be broken

### ISSUE THREAD

**Issue by bebraw** [matubu/speed_highlight_js#16]
**Information**

I tested both on Chromium 92 and Safari 15.1.

**Description**

https://matubu.github.io/speed_highlight_js/examples/ seems to be broken. The page is giving

```
TypeError: Cannot read property 'sub' of undefined
    at tokenize (index.js:36)
    at highlightText (index.js:89)
    at highlightElement (index.js:108)
    at (index):95
```

Maybe some recent change broke it?

**Example**

See above.

**Expected behavior**

I would expect the demo to work.

**Comment by matubu** [comment]
Should be fix now, thank for reporting
